spring.application.name=module1

notification.type = email

#alse we can set environment variables as
#application.properties are over ridden by environment variables , so env variables are priority
#NOTIFICATION_TYPE=SMS
