spring.application.name=module3

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/codingshuttleDb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##to add using data.sql file
#
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql