spring.application.name=springSecurity

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/codingshuttleDb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#security
spring.security.user.name =sadwi
spring.security.user.password = pass

